version: '3'

services:
  green:
    container_name: green
    environment:
      color: "green"
    image: "${DOCKERHUB_USERNAME}/${APP_NAME}:latest"
    ports:
      - "8080:8080"
    deploy:
      replicas: 0
    networks:
      - allreva

  blue:
    container_name: blue
    environment:
      color: "blue"
    image: "${DOCKERHUB_USERNAME}/${APP_NAME}:latest"
    ports:
      - "8081:8080"
    deploy:
      replicas:
        0
    networks:
      - allreva

  redis:
    container_name: redis-dev
    image: redis
    ports:
      - "6379:6379"
    networks:
      - allreva
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx 설정 파일 마운트 (읽기 전용)
      - ./nginx.blue.conf:/etc/nginx/nginx.blue.conf:ro
      - ./nginx.green.conf:/etc/nginx/nginx.green.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - blue
      - green

networks:
  allreva:
    name: allreva
