version: '3'

services:
  green:
    container_name: green
    environment:
      color: "green"
    image: "${DOCKERHUB_USERNAME}/${APP_NAME}:latest"
    ports:
      - "8080:8080"

  blue:
    container_name: blue
    environment:
      color: "blue"
    image: "${DOCKERHUB_USERNAME}/${APP_NAME}:latest"
    ports:
      - "8081:8080"

  redis:
    container_name: redis-dev
    image: redis
    ports:
      - "6379:6379"