version: '3'

services:
  green:
    container_name: green
    environment:
      color: "green"
    image: "${DOCKERHUB_USERNAME}/${APP_NAME}:latest"
    ports:
      - "8080:8080"
    networks:
      - allreva

  blue:
    container_name: blue
    environment:
      color: "blue"
    image: "${DOCKERHUB_USERNAME}/${APP_NAME}:latest"
    ports:
      - "8081:8080"
    networks:
      - allreva

  redis:
    container_name: redis-dev
    image: redis
    ports:
      - "6379:6379"
    networks:
      - allreva
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - allreva

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://allreva:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "concertLike-event:1:1,rent-event:1:1,survey-event:1:1"
    networks:
      - allreva

networks:
  allreva:
    name: allreva
