version: '3'

services:
  green:
    container_name: green
    environment:
      color: "green"
    image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:latest
    ports:
      - "8080:8080"

  blue:
    container_name: blue
    environment:
      color: "blue"
    image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:latest
    ports:
      - "8081:8080"