name: Update Jira issue
on:
  issues:
    types:
      - edited

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update-issue:
    name: Update Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Extract Jira Issue Key
        id: extract-key
        run: |
          TITLE="${{ github.event.issue.title }}"
          JIRA_KEY=$(echo $TITLE | grep -o '\[ARV-[0-9]\+\]' | tr -d '[]')
          echo "jira_key=${JIRA_KEY}" >> $GITHUB_OUTPUT

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Update Jira Issue
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract-key.outputs.jira_key }}
          description: ${{ steps.md2jira.outputs.output-text }}
          summary: ${{ github.event.issue.title }}

      - name: Add comment about update
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: 'Jira Issue Updated: [${{ steps.extract-key.outputs.jira_key }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.extract-key.outputs.jira_key }})'